[package]
name = "iff-parameter"
version = "0.1.0"
authors = ["Johannes <johannes.kreutle111@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
